import Head from 'next/head'
import { useEffect, useState } from 'react'
import ContactCard from '../components/ContactCard'
import DeleteModal from '../components/DeleteModal'
import { Contact, getContactsFromLS, setContactsArray } from '../lib/localStorage'

export default function Home() {
  const [contacts, setContacts] = useState<Contact[]>([])
  const [selectedContact, setSelectedContact] = useState('')
  const [isDeleteModalOpen, setIsDeleteModalOpen] = useState(false)

  const activateDeleteModal = (id: string) => {
    setSelectedContact(id)
    setIsDeleteModalOpen(true)
  }

  const closeDeleteModal = () => {
    setSelectedContact("")
    setIsDeleteModalOpen(!isDeleteModalOpen)
  }

  const deleteContact = () => {
    const newContacts = contacts.filter((element, index) => {
      return element.id !== selectedContact
    })
    setContactsArray(newContacts)
    const newStoredContacts = getContactsFromLS()
    setContacts(newStoredContacts)
  }

  useEffect(() => {
    const storedContacts = getContactsFromLS()
    setContacts(storedContacts)
  }, [])

  return (
    <>
      <Head>
        <title>Contact Book</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {isDeleteModalOpen && (
        <DeleteModal
          deleteContact={deleteContact}
          closeDeleteModal={closeDeleteModal}
          id={selectedContact}
        />
      )}

      <main className='bg-gray-100 min-h-screen'>

        {contacts.length === 0 ? (
          <div>No Contacts found</div>
        ) : (
          <div className='space-y-5 pt-10'>
            {contacts.map(contact => (
              <ContactCard
                key={contact.id}
                id={contact.id}
                name={contact.name}
                phone={contact.phone}
                type={contact.type}
                isOnWhatsapp={contact.isOnWhatsapp}
                profilePicture={contact.profilePicture}
                activateDeleteModal={activateDeleteModal}
              />
            ))}
          </div>
        )}

      </main>
    </>
  )
}
